### ISSUE TITLE
Tab skips twice when focused on text inputs

### ISSUE THREAD

**Issue by yilmaz08** [ggozad/oterm#100]
While editing the chat parameters I've realized that pressing Tab on "System" input or "Parameters" input was going to the next element twice. When on "System" input, it goes to "Parameters" and then quickly goes to "JSON output". It kind of looks like the key is pressed twice but it is not. \
The same behaviour can be seen on the video attached.

I had no idea how to solve this so I am opening an issue.

https://github.com/user-attachments/assets/d6864fd9-a609-4964-964e-015efdfd63d4

OS: Arch Linux
WM: bspwm
Terminal Emulator: alacritty
Installation: Manual (I had just cloned repo and installed packages to work on some stuff)

Thank you in advance!

**Comment by yilmaz08** [comment]
The same thing happens on:

New Chat Page
Multiline prompt entry (it works perfectly on single line)

there must be something broken about multiline entries

**Comment by ggozad** [comment]
Yeah I've noticed the same. I could swear that it didn't always happen which probably means it's a bug in recent textual versions. Will look into it asap, thanks for the detailed report!

**Comment by ggozad** [comment]
> Yeah I've noticed the same. I could swear that it didn't always happen which probably means it's a bug in recent textual versions. Will look into it asap, thanks for the detailed report!

I can confirm the issue is on our side, will fix.
