### ISSUE TITLE
Unable to include image after update

### ISSUE THREAD

**Issue by mik111111** [ggozad/oterm#107]
After a recent update it is no longer possible to include an image with ctrl+p. Ctrl+p now opens some sort of search bar. Has the image functionality been removed or is it now a different key combination? I tried ctrl+a-z but nothing opens the image selection menu.
![Screenshot_20240830_010229](https://github.com/user-attachments/assets/a34f5cb6-f227-4a8f-aa11-fe68008d6473)

**Comment by yilmaz08** [comment]
I have the same problem on AUR package `oterm` and `oterm-git`. However, after cloning the repo in order to try fixing it, I've realized the problem doesn't exist when oterm is launched with `uv run oterm`.

**Comment by ggozad** [comment]
It's my bad, I did npt notice that the latest textual changed the shortcut for the command palette. Will fix asap!

**Comment by ggozad** [comment]
Should be good, please verify.

**Comment by mik111111** [comment]
Works now. Thanks
