### ISSUE TITLE
Newline does not work as expacted

### ISSUE THREAD

**Issue by mcDandy** [ggozad/oterm#117]
I opened a new windows terminal and made sure oterm is not running anywhere else before.
I am running oterm 0.5.2
Problems: 
1. Clicking newline in multiline mode places newline in the wrong place (from second line onwards)
2. Pressing shift+enter sends data to ollama

1. newline position problems
     a. Happens only on and after second line. Did not find what are the rules of placement of newline
     b. Does not matter if ascii or unicode is used.

https://github.com/user-attachments/assets/6440fefc-01cb-48fa-8719-63f6ca25d0ba

**Comment by ggozad** [comment]
I am away for a short holiday, but I can confirm this is an issue. Will fix asap.

**Comment by danyalaytekin** [comment]
Shift enter is still submitting the message for me here on macOS with v0.6.4.  I don't think it did this until I upgraded to 0.6 recently.

**Comment by ggozad** [comment]
@danyalaytekin Can you please let me know which terminal you use? It works fine for me on iTerm.
Also, are you in multi-line mode when you press shitft+enter?

**Comment by danyalaytekin** [comment]
Hi @ggozad, this was in the stock macOS 14.6.1 terminal. I've just tested in iTerm too. I should probably switch over entirely but it has never quite caught on... anyway, my results:

| mode | Terminal | iTerm |
|--|--|--|
| normal | submits | nothing happens |
| multiline | submits | newline |

**Comment by jim-at-jibba** [comment]
I found a similar issue. It works fine in Kitty with no multiplexer. 
But in Kitty with tmux is submits and in Wezterm it also submits.

Thanks

**Comment by ggozad** [comment]
Thank you all for reporting how this works across environments.
I believe fixing this properly is unfeasible as I have to rely on `textual`'s handling of keys and my guess is that it is difficult to do it properly across varied environments.
An alternative would be to allow configurable keymaps. This was introduced in the latest textual release a few days back, I am gonna investigate whether it's a good alternative.
If there are any takers: https://darren.codes/posts/textual-keymaps/

**Comment by ggozad** [comment]
https://github.com/ggozad/oterm/pull/131 allows customizations to key bindings. See the README for how to do that.
If this works for you, I will release asap.

**Comment by IvanTurgenev** [comment]
had to use ctrl+enter, on nixos tmux alacritty
