### ISSUE TITLE
Crashes behind proxy

### ISSUE THREAD

**Issue by gerroon** [ggozad/oterm#128]
I can't run this under WSL Ubuntu session, the VM is set to use http proxy for internet access. 

I used python -m pip to install it under WSL

![image](https://github.com/user-attachments/assets/87d2d0f8-08d8-4b09-8832-899676de0930)

**Comment by gerroon** [comment]
Ok the doc needs to be updated `OLLAMA_URL=http://host:port/api` This is wrong, it should be `OLLAMA_URL=http://host:port`

**Comment by ggozad** [comment]
Thanks @gerroon will fix.
