### ISSUE TITLE
History not saved

### ISSUE THREAD

**Issue by pphuck** [ggozad/oterm#133]
I'm running oterm 0.6.5 on a Chromebook Plus (Linux penguin 6.6.46-04024-g9e7e147b4900) and I'm getting the following error, which seems to be blocking the sqlite history to function -- i.e. no chat log is saved to it, but the chat tab renaming does persist between restarts of oterm.

> Task exception was never retrieved
> future: <Task finished name='Task-597' coro=<ChatContainer.on_submit.<locals>.response_task() done, defined at /home/pp/.local/lib/python3.11/site-packages/oterm/app/widgets/chat.py:127> exception=AttributeError("'Vertical' object has no attribute 'can_view'")>
> Traceback (most recent call last):
>   File "/home/pp/.local/lib/python3.11/site-packages/oterm/app/widgets/chat.py", line 157, in response_task
>     if message_container.can_view(response_chat_item):
>        ^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'Vertical' object has no attribute 'can_view'

I've installed oterm using pip. 

$ pip --version
pip 23.0.1 from /usr/lib/python3/dist-packages/pip (python 3.11)

History does save and function if I comment out the two...

`# if message_container.can_view(response_chat_item):`

...while keeping the two...

`message_container.scroll_end()`

...but I'm sure that's breaking something else I haven't noticed yet. ;-)

**Comment by ggozad** [comment]
Hey, thank you!
It appears that textual has removed `can_view` from widgets. I will fix and release asap.
