### ISSUE TITLE
[feature request]  ability to switch on chat names

### ISSUE THREAD

**Issue by mcDandy** [ggozad/oterm#136]
I have problems with fastly changing seasions since I updated from 6.3. The line on top is 2 pixels wide. Too thin to quickly switch chats (also you do not know what the chat is about without switching to it). Clicking input Ollama and then next chat is also too slow. (keyboard shortcut does not work due to conflict, need to target input field first)

![image](https://github.com/user-attachments/assets/698db84d-e9ce-4525-a170-bf6eeb8b8756)

**Comment by mcDandy** [comment]
Oh you can click below 😅. The text would still help...

**Comment by ggozad** [comment]
Ops, this is my bad, will fix asap...
