### ISSUE TITLE
PyPI package version 0.1.11 missing `format` column on chat table

### ISSUE THREAD

**Issue by hiltonm** [ggozad/oterm#14]
Hello, I can see you added the `format` column on setup.py on your last commit here, but you didn't publish this code on pypi as 0.1.11, so the column is not being created on new databases and it crashes. Thanks for the app, cheers!

**Comment by Lambda-Logan** [comment]
<img width="379" alt="image" src="https://github.com/ggozad/oterm/assets/68832147/b236c54f-88d9-4e9b-8a92-29f275c1e3a0">
Just trying it out for the first time, same. But the color scheme looks divine!

**Comment by ggozad** [comment]
Ops I am so sorry, I will fix once I am near to a computer.

**Comment by ggozad** [comment]
Should be good :)
