### ISSUE TITLE
Light theme is not light enough

### ISSUE THREAD

**Issue by suhr** [ggozad/oterm#21]
![2023-12-16-201140_3840x2160_scrot](https://github.com/ggozad/oterm/assets/65870/b4711ee2-b63a-4abb-9730-68e28f28fba9)

The input field is dark as well as code blocks.

**Comment by ggozad** [comment]
I am considering dropping the light/dark theme switcher altogether...
`textual` seems to have pretty limited support for theming and I am reluctant to put time and effort in maintaining one of my own.
Unless there are any takers?

**Comment by ggozad** [comment]
FYI related to https://github.com/Textualize/textual/issues/3997

**Comment by ggozad** [comment]
@suhr if you have the time please test this closes #21. I think it does, but happy to make changes.
