### ISSUE TITLE
iTerm2 Problems on OSX

### ISSUE THREAD

**Issue by oderwat** [ggozad/oterm#31]
I tried running this on iTerm2 in OSX and ran into some problems:

- All new chats are "JSON output" and I can't change the field
- Using <TAB> on "chat" will tab into the Template and using it again will only add tabs inside the template widget. I need to use <SHIFT-TAB> to reach other widgets.
- The format is always "JSON output" and I can't find a way to disable it. I thought of using just enter/return, but it does nothing.

Another "problem": Adding `export OLLAMA_URL=http://$OLLAMA_HOST:11434/api` is trivial but as all my other ollama based tools are just happy with using `$OLLAMA_HOST` I wished that oterm also would just use this or at least if there is no OLLAMA_URL in the environment.

**Comment by ggozad** [comment]
Hey there,
JSON output is disabled by default. You need to click it to enable it.
This is off:
<img width="229" alt="json_off" src="https://github.com/ggozad/oterm/assets/183103/0ea0108d-a61f-406f-a2e0-38bf9c0c0568"> 
This is on:
<img width="203" alt="json_on" src="https://github.com/ggozad/oterm/assets/183103/73b92c80-aa67-4362-ac8b-d20c432527b3">

I am afraid it's one of these times where using the mouse is necessary. I will try to figure out how to not capture `TAB` in the textareas but not sure it's possible. Keeping this open till then.

**Comment by oderwat** [comment]
All models show JSON as enabled. Mouse is not working (I usually have mouse support switched off for terminals anyway).

![oterm](https://github.com/ggozad/oterm/assets/719156/9320626e-9e48-4c77-a8ce-cc2ab2af759e)

**Comment by ggozad** [comment]
Please look what I posted. This is the "off" state for the checkbox. I am afraid you won't be able to use oterm without mouse support.

**Comment by oderwat** [comment]
Well. It did output json for me while it showed the state  as you can see in the video below. I did find out that it actually does switch the state when you are on it, and press space. It is just not visibel. Have a look at the video (first time I press 1. time space, 2. time I press space twice). From you image I thought "if it is not black" it is enabled and thought that "white" may be the green. But anyway. I do not need a mouse (and if you do a terminal programm you should think again using a library that only supports a checkbox with a mouse, lol). But the terminal needs to get updated correctly. I use a lot of terminal tools, never had such strange effects though.

![oterm2](https://github.com/ggozad/oterm/assets/719156/cf16dd04-4ace-4d79-89e9-dacebad84e6a)

What about the ENV variable? Wouldn't it be smarter to support the same ENV variable that ollama is using anyway?

P.S.: i wonder why you close something as completed when it obviously is not completed. And I already have the feeling that you think I work against you. So thanks for the tool, but I guess I need to make a fork then. Hopefully you do accept PRs.

**Comment by ggozad** [comment]
I am sorry I offended you. 
I am really not sure how to help you. I don't see the checkbox turning green in your video. I know for sure the default is off (which is not green). It is perhaps unfortunate that the checkbox from `textual` has an `x` inside on the off state, but I can't make every single widget from scratch, that's the one provided.
I am not going to get into a fight about whether one should use the mouse or not. `textual` which `oterm` uses provides a UI similar to your typical GUI which makes it necessary. I will accept PR that makes everything work with a keyboard alone.
Please open another issue for the env var, or even better make a pull request.

This issue was closed because it's 3 issues, one of which I cannot reproduce (JSON) , another that I will not work on (mouse), and a third that came as an afterthought.

**Comment by oderwat** [comment]
I know that it does not turn green, but it changes the output. That is the whole point of the second video. This also explains why I thought it is always the default, because it was actually enabled ("hidden") as I was playing around and to I got the impression that they are always on by default.

About the mouse: I actually meant, that I can't believe that a terminal library does not support toggling a widget by mouse only. And as I wrote: It toggles when I use space while that widget is selected (in the result, but not visibly). So the real problem with that seems that the UI is not getting updated.

I understand that you can't or won't change every widget. I would expect that a terminal library can handle something like iTerm2 though. In the original terminal it does visual toggle using space and mouse. So it may even be just a problem with my color scheme in iTerm2. This terminal library does not seem to be very well designed though :)

About the "multiple topics in one issue": I see :) Sorry about that.
