### ISSUE TITLE
Can't forget the chat when in multi-line mode

### ISSUE THREAD

**Issue by suhr** [ggozad/oterm#33]
Also Ctrl+L does not switch back from multi-line mode to single-line mode.

**Comment by ggozad** [comment]
Hah!
So what's happening is that when you switch to multiline mode the "textarea" widget used is listening for ctrl+x, ctrl+l and others. Here's the reference for all the bindings: 

https://textual.textualize.io/widgets/text_area/#bindings

I am not sure how to deal with this. One could disable the bindings but that's not great either. Finding new bindings is also not acceptable. Any ideas?
