### ISSUE TITLE
Scrolling Behavior Issue on macOS

### ISSUE THREAD

**Issue by ecthelionvi** [ggozad/oterm#40]
I am experiencing an issue with the scrolling behavior in `oTerm` where the content appears to bounce up and down when I try to scroll using the trackpad on my Macbook Air. Additionally,  the scrollbar will seem to get stuck and then bounce up and down when you try and move it.

I've attached a screen recording that demonstrates the bouncing scrolling effect:
![CleanShot 2023-12-26 at 19 25 42](https://github.com/ggozad/oterm/assets/21297100/898a86c1-03ab-40a4-a510-d709d1489be1)

**Comment by ggozad** [comment]
Hey there, thanks :)
I will look into it asap, not sure I can fix it though.

**Comment by ggozad** [comment]
Would you be able to comment on how to reproduce this? I've tried adding a few chats with code embedded and tried on iTerm as well as kitty (which I think is the one I see used in your video) but can't seem to be able to reproduce. Scrolling seems to work as expected for me.
