### ISSUE TITLE
Can't Copy/paste or run generated code.

### ISSUE THREAD

**Issue by iplayfast** [ggozad/oterm#41]
Tried out oterm (looks pretty good). 
I told Mistral that I need a snake game using the pygame library.
It wrote out a bunch of code.

I could not do anything with the code. 

At the very least you should be able to copy paste. 
Another option is have a button when code is generated that when clicked on, allows to save generted code to file, or run the code.

**Comment by ggozad** [comment]
- Away in the mountains, but you can right click to copy iirc

**Comment by iplayfast** [comment]
Nope doesn't work.

**Comment by ggozad** [comment]
Pretty sure it should... right click on the cell you want to copy, you should see a brief flash and copy is done.
If not back in a few days...

**Comment by ggozad** [comment]
Hey there, I just tested and it works fine with simple mouse click on cell. Gonna close this but if you still have trouble feel free to reopen.
