### ISSUE TITLE
Asian language response instead of English

### ISSUE THREAD

**Issue by mslinn** [ggozad/oterm#49]
I queried &ldquo;What was the color of George Washington's white horse?&rdquo;, and after a few minutes got a response in an unknown language:

![oterm3](https://github.com/ggozad/oterm/assets/485818/08a7c1a7-5aeb-4d5d-9f67-30704acc7efa)

Running the same query with samantha-mistral did not have this problem:

![oterm4](https://github.com/ggozad/oterm/assets/485818/09c44bfc-d8f7-4283-a176-d17fa5a651fb)

**Comment by ggozad** [comment]
Hey Mike, I am afraid oterm merely shows you the responses it gets from Ollama. It does not generate anything. If I remember correctly llava is bilingual using Chinese and English so it's probably just confused.
