### ISSUE TITLE
suggestion: view or export model info/chat metadata

### ISSUE THREAD

**Issue by mschwaig** [ggozad/oterm#57]
The model selection screen makes it possible to set the model, the system prompt and the message template.

Once a chat is created it is no longer possible to view how the system prompt, the message template or other parameters are set.

Since I often play around with different system prompts,
I would like to be able to view those settings from the model selection screen later on in the UI or export them to the clipboard.

**Comment by ggozad** [comment]
You are right, I have been wanting to do this for a long while but never get the time.
That said, it IS a rather easy thing to do. Would really like someone stepping in and taking it (hint) 🤓
