### ISSUE TITLE
How can I trigger shortcuts?

### ISSUE THREAD

**Issue by t18n** [ggozad/oterm#6]
![image](https://github.com/ggozad/oterm/assets/14198542/fc192459-2862-4bb6-a67b-bf2d38b1a340)

How can I trigger these shortcuts? I am using Mac and when I type `Shift + N`, it is just treated as the chat input. `Ctrl + Shift + N` or `CMD + Shift + N` doesn't work as well.

**Comment by ggozad** [comment]
You need no modifier. Just `N`. :)

**Comment by t18n** [comment]
I tried it but it just type `n` into the chat. I use Wezterm. What terminal do you use?

**Comment by ggozad** [comment]
If you are focused on an input field, whatever you type goes in there. Try for example TAB or ESCAPE first.
