### ISSUE TITLE
Enhancement: Refined selection capability

### ISSUE THREAD

**Issue by aaronsb** [ggozad/oterm#67]
## Human me disclaimer
I want to see a refinement of clipboard copy operation. I wrote a general enhancement description, and refined it through GPT. I think the refined statement is clearer by far that what I wrote, and makes a lot of sense. It follows below:

## Summary
The current user interface supports navigation through tabbing, mouse interactions, and scrolling to access conversation history. A gap exists when interacting with responses containing markdown quoted content, as users cannot selectively copy content within these quotes. This request aims to introduce a capability for users to choose specifically between copying only the content within markdown quotes or the entire response, enhancing interaction precision with the conversation history.

## Description
Users navigate the user interface using tabbing, mouse clicks, and scrolling, enabling them to select items in the history for copying to the clipboard. In dialog sessions with a mix of responses, including markdown quoted content, the interface does not currently offer an option to copy just the content within these quotes. This limitation affects the process of retrieving specific information from extensive conversations, particularly when the information is embedded in quotes.

## Enhancement Detail
The enhancement focuses on allowing users to make a "sub-select" or "recursive select" within a response that contains markdown quoted content. This added functionality will enable a more detailed level of interaction with the content, allowing users to copy only the content within the markdown quotes to the clipboard based on their selection point:

- **When a user clicks on a markdown quoted item**, the system will copy only the content within the markdown quotes to the clipboard.
- **When a user clicks outside the markdown quoted area of a response**, the system will copy the entire response, including the markdown quoted content, maintaining the current method of interaction for users needing to copy the response.

## Assumptions

- Dialog sessions may be lengthy and include a variety of responses.
- Some responses will contain valuable information within markdown quotes.
- Navigation through the application involves a combination of tabs, arrow keys, and mouse input.

### Acceptance Criteria

- **Selective Copy Functionality**
  - The system must enable users to copy content within markdown quotes by clicking on the quoted text, ensuring only the selected quoted content is copied to the clipboard.
- **Full Response Copy Functionality**
  - When clicking outside the markdown quoted text, the system must copy the entire response, including the quoted content, thereby not altering the interaction for copying full responses.
- **Consistency Across Conversations**
  - This feature must work consistently in dialog sessions of any length and complexity, facilitating specific information retrieval without the conversation's extent impacting performance.
- **Integration with Current Navigation Methods**
  - The feature's introduction should not disrupt current navigation practices within the application, ensuring that it complements existing methods like tabbing, arrow keys, and mouse input.

By implementing this feature, the application will provide users with enhanced control over the content they wish to extract from the conversation history, particularly useful in dialog sessions rich in specific, quotable information.

**Comment by ggozad** [comment]
Oh wow my first ChatGPT PR 😆
This is an interesting one, not sure how complex it is, but will see if I can find some time to investigate.

**Comment by kion** [comment]
I think oterm is an amazing piece of software! And thus far this is probably the main feature I am missing in it. Would love to see this implemented.

**Comment by ggozad** [comment]
Hey!
In #70 I patch the widget that is responsible for displaying code blocks, so that if the user clicks inside a code block only the contents of the code block are copied. Clicking outside a code block copies the entire message.

I think this is enough to cover the most common case. Feedback welcome!

**Comment by ggozad** [comment]
Gonna take the lack of feedback as silent approval and release :)
