### ISSUE TITLE
Multiline paste doesn't work with non-expanded chat input

### ISSUE THREAD

**Issue by t18n** [ggozad/oterm#7]
When the chat input is collapsed, multiline paste only paste in the first line
![image](https://github.com/ggozad/oterm/assets/14198542/6afc7c37-d563-4539-8385-36239c7bdf36)

but when I expanded it before paste, it works perfectly
![image](https://github.com/ggozad/oterm/assets/14198542/7ee7b722-ba50-44fe-9c41-549324f33526)

Expected behavior: When paste multiple lines, the input field should receive the whole clipboard entry and the chat should automatically expand to accomodate long text

**Comment by ggozad** [comment]
I've spent some time on this yesterday but struggled with overriding the paste behaviour in textual. This will probably take a bit longer.

**Comment by ggozad** [comment]
Fixed on main, will probably get some more stuff in and make a release tomorrow.
