### ISSUE TITLE
 OLLAMA_HOST: 0.0.0.0:11434 is not working on windows 11 and perhaps a related bug changing local IP to the same default IP by Ollama.

### ISSUE THREAD

**Issue by amonpaike** [ggozad/oterm#71]
`OLLAMA_HOST  "0.0.0.0:11434" is not working on windows 11`
 
 by changing OLLAMA_HOST in the windows path in 127.0.0.1:11434 (defaut ollama ip on windows)  it conflicts with the Ollama server itself or with other ollama related apps, They simply don't work. Then I change the same local ip inside [oterm config.y](https://github.com/ggozad/oterm/tree/main/oterm/config.py)  and everything works fine, except one thing that happens, when I select `CTRL-N `  and select an AI model oterm crashes and gives me this screen.. 
 
![image](https://github.com/ggozad/oterm/assets/884282/7ff002ec-b54e-4b32-997f-f243bc31d91e)

Then when I reload oterm, and the new chat is started with the selected model and everything works correctly.. I'm not sure if the change of the local IP address is related to this "bug"

**Comment by ggozad** [comment]
Hey there!
You do not need to customize `config.py`. It should be enough to set the environment variable `OLLAMA_HOST`.  I think in windows you would do 
```
set OLLAMA_HOST="127.0.0.1:11434"
```

Could you please open another issue about the crash and include the entire traceback rather than a screenshot?

**Comment by amonpaike** [comment]
> set OLLAMA_HOST="127.0.0.1:11434"

this is what I did the first few times, but it conflicted with ollama itself and the ollama server didn't start and it didn't let me access the various llm models

**Comment by amonpaike** [comment]
> Could you please open another issue about the crash and include the entire traceback rather than a screenshot?

sorry but it's not clear to me how to do it, the traceback tells me to use --dev for all errors, but the way I do it seems to be wrong.. I tried `ollama --dev` but it doesn't work

**Comment by ggozad** [comment]
> > Could you please open another issue about the crash and include the entire traceback rather than a screenshot?
> 
> sorry but it's not clear to me how to do it, the traceback tells me to use --dev for all errors, but the way I do it seems to be wrong.. I tried `oterm --dev` but it doesn't work
> 
> ![image](https://private-user-images.githubusercontent.com/884282/320081038-31cf2e84-956a-4f53-a893-d061b5ab5a69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMzcyNjAsIm5iZiI6MTcxMjMzNjk2MCwicGF0aCI6Ii84ODQyODIvMzIwMDgxMDM4LTMxY2YyZTg0LTk1NmEtNGY1My1hODkzLWQwNjFiNWFiNWE2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNVQxNzA5MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZWZmYjdhZTIyMzc4ZTIzMThiZTVjZGU3ODMxYTE4YWRmNzQ2N2MwMGNmNTM0MzY1MzVlNmQ0NzZiMTBjY2Y0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sKDYFC0pJjatUAdKgxUM5scPIsgtxkB5fAPHlOk5vyY)

Just make a new ticket and instead of adding a screenshot, copy/paste the traceback.

**Comment by amonpaike** [comment]
> * Start Ollama. Either using the docker image or by running `ollama serve`. It should start on the default port which is 11434.
> * On a separate terminal start `oterm`.
>   Does that work?

Ollama server is already started and working.

I reset config.py to 0.0.0.0 and then  `set OLLAMA_HOST="127.0.0.1:11434"`

then as soon as I started oterm this mess emerged:

`C:\Users\noki>set OLLAMA_HOST="127.0.0.1:11434"

C:\Users\noki>oterm
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\noki\AppData\Local\Programs\Python\Python311\Scripts\oterm.exe\__main__.py", line 4, in <module>
  File "C:\Users\noki\AppData\Local\Programs\Python\Python311\Lib\site-packages\oterm\cli\oterm.py", line 6, in <module>
    from oterm.app.oterm import app
  File "C:\Users\noki\AppData\Local\Programs\Python\Python311\Lib\site-packages\oterm\app\oterm.py", line 7, in <module>
    from oterm.app.chat_edit import ChatEdit
  File "C:\Users\noki\AppData\Local\Programs\Python\Python311\Lib\site-packages\oterm\app\chat_edit.py", line 5, in <module>
    import ollama
  File "C:\Users\noki\AppData\Local\Programs\Python\Python311\Lib\site-packages\ollama\__init__.py", line 34, in <module>
    _client = Client()
              ^^^^^^^^
  File "C:\Users\noki\AppData\Local\Programs\Python\Python311\Lib\site-packages\ollama\_client.py", line 65, in __init__
    super().__init__(httpx.Client, host, **kwargs)
  File "C:\Users\noki\AppData\Local\Programs\Python\Python311\Lib\site-packages\ollama\_client.py", line 55, in __init__
    base_url=_parse_host(host or os.getenv('OLLAMA_HOST')),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\noki\AppData\Local\Programs\Python\Python311\Lib\site-packages\ollama\_client.py", line 723, in _parse_host
    port = split.port or port
           ^^^^^^^^^^
  File "C:\Users\noki\AppData\Local\Programs\Python\Python311\Lib\urllib\parse.py", line 182, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as '11434"'

C:\Users\noki>
`

**Comment by amonpaike** [comment]
for more information, with config.py set to 0.0.0.0:11434 , oterm starts, it also sees the various llm models, but once a model is started if I ask a question, the llm simply doesn't start the answer process (not even the three graphic dots come out.)

**Comment by amonpaike** [comment]
> Just make a new ticket and instead of adding a screenshot, copy/paste the traceback.

copying and pasting from the terminal with the ashii traceback graphics comes out an unreadable mess, that's why I put a screenshot, I'll open a new ticket and paste both

**Comment by ggozad** [comment]
The OLLAMA_HOST issue should be fixed on main, closing this as we have the rest in separate tickets.

**Comment by deimo72** [comment]
<img width="936" alt="Image" src="https://github.com/user-attachments/assets/60d3b0d1-e9da-48ea-8be8-f3b25426eecc" />

I had the same error and I solved it using
export OLLAMA_HOST=http://0.0.0.0:11434
