### ISSUE TITLE
Suggestion: Allow scrolling during generation

### ISSUE THREAD

**Issue by dannydarvish** [ggozad/oterm#79]
In its current state, oterm scrolls all the way to the bottom every time a new token is generated. This can be frustrating when trying to scroll up to read text while a response is still being generated.

**Comment by ggozad** [comment]
Hey there!
What would the default behavior be instead? I sort of wanted it to be like that cause I like to read the response as it is being generated, but perhaps this is not what most people want.
I am a bit reluctant to NOT scroll, but maybe others can chime in?

**Comment by dannydarvish** [comment]
In my opinion, it should auto-scroll down as the tokens are being generated **unless** the user moves the scroll bar up, in which case it should unlock and stay where it was put. And when it is dragged to the bottom again, it should continue to auto-scroll. This would feel consistent with other terminal programs I've used. Just my two cents.

**Comment by ggozad** [comment]
I think we are in agreement and in the right direction. Left some comments in the @dannydarvish 's PR, we should be able to fix this soon.
