### ISSUE TITLE
Suggestion: Connect to remote ollama instance

### ISSUE THREAD

**Issue by adan89lion** [ggozad/oterm#80]
I'm wondering if it's possible to establish a remote connection between my oterm client on my MacBook and an ollama instance running on my PC. Currently, I'm using oterm and ollama locally on my MacBook on battery, and I'd like to take advantage of my more powerful PC at home.

**Comment by ggozad** [comment]
Hey,
Yes this should be easily done. We support the `OLLAMA_URL` environment variable which you should set to correspond to your PC's address/port. This should work just fine in a LAN environment, or you can use something like `ngrok` if you want to expose the server over the internet. Be aware there is no authentication in that case so you are essentially open to abuse.

**Comment by adan89lion** [comment]
I have tried to set the environment variable `OLLAMA_URL` to my PC ollama instance; however, oterm still tries to reach `http://0.0.0.0:11434/api/tags`

Here's my steps:
1. Set `OLLAMA_HOST` on my PC to listen to 0.0.0.0 (which works because I have a [Open WebUI](https://github.com/open-webui/open-webui) instance and can connect to it remotely)
2. Set `OLLAMA_URL` to my PC's local IP address
3. oterm displays `ConnectError: [Errno 111] Connection Refused` with multiple `GET` attempts to reach `http://0.0.0.0:11434/api/tags`

**Comment by adan89lion** [comment]
Hello,

I confirm that using the command provided by @lainedfles works. (`OLLAMA_URL="http://192.168.0.100:11434/api" oterm`) It was my mistake that I didn't add `export` in front of the environmental variables in my shell :(. Thank you all for your assistance :)
