### ISSUE TITLE
Suggestion: keybind to send message

### ISSUE THREAD

**Issue by ThatOneCalculator** [ggozad/oterm#86]
Being able to either send a message with <kbd>Enter</kbd> and make a newline with  <kbd>Ctrl</kbd> + <kbd>Enter</kbd> or send a message with <kbd>Ctrl</kbd> + <kbd>Enter</kbd> and make a newline with <kbd>Enter</kbd> would be great instead of having to click the "Post" button.

**Comment by ggozad** [comment]
I am guessing you are referring to the case where the input is expanded right (multi-line) ? I remember this being my intention, I will revisit once I get some time and see if I can fix it to do that.

**Comment by ggozad** [comment]
Ended up using the standard <kbd>Enter</kbd> for posting, <kbd>Shift+Enter</kbd> for new line.
