### ISSUE TITLE
I want to move a conversation from ollama terminal to oterm. Text is not visible but AI has knowagle of it when editing database.

### ISSUE THREAD

**Issue by mcDandy** [ggozad/oterm#98]
I opened the database putting tokenised input in, The input before tokenisation was <start_of_turn>user text<end_of_turn><start_of_turn>model ... <end_of_turn> and so forth. tokeniser added <bos> at the beginning before turning it into numbers. Total lenght 22k tokens. What am I doing wrong? I don't speek tokeneese fluently.

**Comment by ggozad** [comment]
Hey, `context` is not tokenized input, rather an embedding of the entire conversation. 
I am not sure how one would go about obtaining that from an entire conversation....
You can wait til https://github.com/ggozad/oterm/pull/95 eventually makes it into `oterm` which will make this easy.
I am afraid I can't really help beyond this, so going to close.
